#!/usr/bin/env python3
"""
The Complete AI Agent Dev Loop — ACID for AI Agents
====================================================

PLAN → BUILD → FAIL → REWIND → FIX → SUCCEED → NEVER PAY TWICE

This script demonstrates the full 4-layer stack that nobody else has:

    Layer 1: Planning Mode — Agent thinks before it acts
    Layer 2: Agent Execution — Agent runs the plan
    Layer 3: agent-vcr — Records everything (JSONL on disk)
    Layer 4: Golden Run Cache — Same task, 80% fewer tokens, instant

Usage:
    python examples/acid_golden_run.py
"""

from __future__ import annotations

import os
import shutil
import time
from pathlib import Path
import sys

sys.path.insert(0, str(Path(__file__).parent.parent / "src"))

from agent_vcr import VCRRecorder, FrameMetadata, FrameType
from agent_vcr.golden_cache import GoldenRunCache, CostLedger
from agent_vcr.integrations.openhands import ACIDWorkspace


# ── Pretty Printing ──────────────────────────────────────────────────────────

BOLD = "\033[1m"
DIM = "\033[2m"
RED = "\033[91m"
GREEN = "\033[92m"
YELLOW = "\033[93m"
CYAN = "\033[96m"
MAGENTA = "\033[95m"
RESET = "\033[0m"
BG_RED = "\033[41m"
BG_GREEN = "\033[42m"


def banner(text: str, color: str = CYAN):
    width = 72
    print(f"\n{color}{BOLD}{'━' * width}")
    for line in text.strip().split("\n"):
        print(f"  {line}")
    print(f"{'━' * width}{RESET}\n")


def step(icon: str, msg: str, color: str = ""):
    print(f"  {color}{icon}  {msg}{RESET}")


def cost_box(label: str, tokens: int, cost: float, latency: float, color: str):
    print(f"  {color}┌─────────────────────────────────────────┐")
    print(f"  │  {label:<39}│")
    print(f"  │  Tokens:  {tokens:>10,}                    │")
    print(f"  │  Cost:    ${cost:>9.4f}                    │")
    print(f"  │  Latency: {latency:>8.0f}ms                    │")
    print(f"  └─────────────────────────────────────────┘{RESET}")


# ── Simulated Agent Steps ────────────────────────────────────────────────────
# Each step simulates an LLM call with token usage and cost, mimicking what
# an OpenHands agent would do in a real execution.

PLAN_STEPS = [
    {"node": "planner", "action": "Analyze task requirements", "tokens": 1200, "cost": 0.0036, "latency": 850},
    {"node": "planner", "action": "Generate PLAN.md with architecture", "tokens": 2400, "cost": 0.0072, "latency": 1200},
    {"node": "clarifier", "action": "Confirm approach with user", "tokens": 600, "cost": 0.0018, "latency": 400},
]

BUILD_STEPS_BAD = [
    {"node": "coder", "action": "Create project structure", "tokens": 800, "cost": 0.0024, "latency": 600},
    {"node": "coder", "action": "Write base models", "tokens": 1500, "cost": 0.0045, "latency": 900},
    {"node": "coder", "action": "Implement API routes", "tokens": 2000, "cost": 0.0060, "latency": 1100},
    {"node": "coder", "action": "Write monolithic handler (BAD)", "tokens": 3200, "cost": 0.0096, "latency": 1800},
    {"node": "coder", "action": "Generate 200 lines spaghetti", "tokens": 4000, "cost": 0.0120, "latency": 2200},
    {"node": "tester", "action": "Run tests → CRASH", "tokens": 900, "cost": 0.0027, "latency": 500},
]

BUILD_STEPS_GOOD = [
    {"node": "coder", "action": "Write clean service layer", "tokens": 1800, "cost": 0.0054, "latency": 1000},
    {"node": "coder", "action": "Write modular handlers", "tokens": 1600, "cost": 0.0048, "latency": 900},
    {"node": "tester", "action": "Run tests → ALL PASS ✓", "tokens": 700, "cost": 0.0021, "latency": 450},
]


def simulate_step(
    recorder: VCRRecorder,
    acid: ACIDWorkspace,
    step_info: dict,
    workspace: Path,
    step_num: int,
) -> dict:
    """Simulate an agent step with realistic LLM metadata."""
    time.sleep(0.15)  # Simulate latency feel

    # Write a file to the workspace to simulate real FS side effects
    action_file = workspace / f"step_{step_num}_{step_info['node']}.py"
    action_file.write_text(
        f"# {step_info['action']}\n"
        f"# Generated by {step_info['node']} agent\n"
        f"print('Step {step_num}: {step_info['action']}')\n"
    )

    output = {
        "action": step_info["action"],
        "status": "completed",
        "files_modified": [str(action_file.name)],
    }

    # Record in VCR with full LLM metadata
    recorder.record_step(
        node_name=step_info["node"],
        input_state={"step": step_num, "task": step_info["action"]},
        output_state=output,
        metadata=FrameMetadata(
            latency_ms=step_info["latency"],
            tokens_used=step_info["tokens"],
            tokens_input=step_info["tokens"] // 3,
            tokens_output=step_info["tokens"] * 2 // 3,
            cost_usd=step_info["cost"],
        ),
    )

    # SAVEPOINT via ACID
    acid.savepoint(output, node_name=step_info["node"])

    return output


def run_full_demo():
    """The complete 60-second visceral demo."""
    workspace = Path("/tmp/acid_agent_workspace")
    vcr_dir = Path("/tmp/acid_agent_workspace/.vcr")
    golden_dir = Path("/tmp/acid_agent_workspace/.vcr/golden")

    # Clean slate
    if workspace.exists():
        shutil.rmtree(workspace)

    banner(
        "THE COMPLETE AI AGENT DEV LOOP\n"
        "PLAN → BUILD → FAIL → REWIND → FIX → SUCCEED → NEVER PAY TWICE\n"
        "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
        "4 Layers — Built by One Person — Nobody Else Has This",
        MAGENTA,
    )

    task = "Build a REST API for user authentication with JWT tokens"

    # ═══════════════════════════════════════════════════════════════════
    # RUN 1: THE ORIGINAL RUN (Fail → Rewind → Fix → Succeed)
    # ═══════════════════════════════════════════════════════════════════

    banner("RUN 1: ORIGINAL EXECUTION", CYAN)

    # ── Layer 1: Planning Mode ────────────────────────────────────────
    step("📋", f"Task: {BOLD}{task}{RESET}")
    print()

    recorder = VCRRecorder(output_dir=str(vcr_dir))
    acid = ACIDWorkspace(str(workspace), recorder=recorder)
    acid.begin(session_id="run_001")

    step("🧠", f"{BOLD}LAYER 1: Planning Mode{RESET} — Agent thinks before it acts", YELLOW)
    print()

    step_num = 0
    for s in PLAN_STEPS:
        step_num += 1
        simulate_step(recorder, acid, s, workspace, step_num)
        step("  ✓", f"Step {step_num}: {s['action']}", DIM)

    # Write PLAN.md
    plan_md = workspace / "PLAN.md"
    plan_md.write_text(
        "# Authentication API Plan\n\n"
        "## Architecture\n"
        "- Clean service layer pattern\n"
        "- JWT token management\n"
        "- Modular route handlers\n\n"
        "## Steps\n"
        "1. Create project structure\n"
        "2. Write base models\n"
        "3. Implement API routes\n"
        "4. Write service layer\n"
        "5. Add tests\n"
    )
    acid.savepoint({"plan": "PLAN.md written"}, node_name="planner")
    step("📄", f"PLAN.md written → {GREEN}Agent has a plan{RESET}")
    print()

    # ── Layer 2: Execution (BAD PATH) ────────────────────────────────
    step("⚡", f"{BOLD}LAYER 2: Agent Execution{RESET} — OpenHands runs the plan", YELLOW)
    print()

    rewind_point = step_num  # Save this for rollback

    for s in BUILD_STEPS_BAD:
        step_num += 1
        simulate_step(recorder, acid, s, workspace, step_num)
        if "BAD" in s["action"] or "CRASH" in s["action"]:
            step("  ✗", f"Step {step_num}: {s['action']}", RED)
        else:
            step("  ✓", f"Step {step_num}: {s['action']}", DIM)

    # Write the spaghetti file
    spaghetti = workspace / "monolith.py"
    with open(spaghetti, "w") as f:
        f.write("# MONOLITHIC HANDLER - This is the wrong architecture\n")
        f.write("class GodObject:\n")
        for i in range(200):
            f.write(f"    def do_thing_{i}(self): pass  # spaghetti line {i}\n")

    print()
    step("💀", f"{RED}{BOLD}FAILURE at step {step_num}!{RESET}", RED)
    step("📁", f"Files in workspace: {[f.name for f in workspace.iterdir() if f.is_file()]}")

    total_files = len([f for f in workspace.iterdir() if f.is_file()])
    step("📊", f"Total files created: {total_files} (including 200-line monolith.py)")
    print()

    # ── Layer 3: agent-vcr shows the failure ─────────────────────────
    step("📼", f"{BOLD}LAYER 3: agent-vcr{RESET} — Recorded {len(recorder.get_frames())} frames", YELLOW)

    frames = recorder.get_frames()
    error_frame = frames[-1]
    step("🔍", f"Failed at: {error_frame.node_name} → {error_frame.output_state.get('action', '')}")
    step("💸", f"Tokens burned so far: {sum(f.metadata.tokens_used or 0 for f in frames):,}")
    step("💰", f"Money wasted: ${sum(f.metadata.cost_usd or 0 for f in frames):.4f}")
    print()

    # ── ROLLBACK ─────────────────────────────────────────────────────
    banner("⏪ ROLLBACK TO STEP 3", RED)
    step("🔄", "Rewinding BOTH filesystem AND memory state...", YELLOW)

    acid.rollback(to_frame_index=rewind_point)
    recorder = acid.recorder  # Get the forked recorder

    files_after = [f.name for f in workspace.iterdir() if f.is_file()]
    step("📁", f"Files after rollback: {files_after}")
    assert "monolith.py" not in files_after, "Rollback failed!"
    step("✅", f"{GREEN}{BOLD}ROLLBACK SUCCESS — monolith.py is GONE from disk{RESET}")
    step("✅", f"{GREEN}World rewound. Not just the object — the actual filesystem.{RESET}")
    print()

    # ── RESUME: Good path ────────────────────────────────────────────
    banner("▶️  RESUME FROM STEP 3 — BETTER PATH", GREEN)

    for s in BUILD_STEPS_GOOD:
        step_num += 1
        simulate_step(recorder, acid, s, workspace, step_num)
        step("  ✓", f"Step {step_num}: {s['action']}", GREEN)

    print()
    step("✅", f"{GREEN}{BOLD}ALL TESTS PASS — Agent succeeded!{RESET}")

    # ── COMMIT ───────────────────────────────────────────────────────
    acid.commit()
    step("🔒", f"{GREEN}COMMIT — Successful path locked into main branch{RESET}")
    print()

    # ── Save as Golden Run ───────────────────────────────────────────
    banner("⭐ SAVING AS GOLDEN RUN", YELLOW)

    cache = GoldenRunCache(cache_dir=str(golden_dir))
    fingerprint = cache.save_golden_run(task=task, recorder=recorder, tags=["auth", "jwt"])

    step("⭐", f"Golden path saved with fingerprint: {BOLD}{fingerprint}{RESET}")
    step("💾", f"Cached at: {golden_dir / f'{fingerprint}.vcr'}")

    run1_tokens = sum(f.metadata.tokens_used or 0 for f in recorder.get_frames())
    run1_cost = sum(f.metadata.cost_usd or 0 for f in recorder.get_frames())
    run1_latency = sum(f.metadata.latency_ms or 0 for f in recorder.get_frames())

    print()
    cost_box("RUN 1: Original Execution", run1_tokens, run1_cost, run1_latency, YELLOW)

    # Show git log
    print(f"\n  {DIM}Git history:{RESET}")
    os.system(f"cd {workspace} && git log --oneline --graph --all 2>/dev/null | head -10 | sed 's/^/    /'")

    # ═══════════════════════════════════════════════════════════════════
    # RUN 2: GOLDEN REPLAY — Same task, $0.00, instant
    # ═══════════════════════════════════════════════════════════════════

    banner("RUN 2: GOLDEN REPLAY — SAME TASK", MAGENTA)
    step("🔁", f"Task: {BOLD}{task}{RESET}")
    step("⭐", "Golden run found in cache! Replaying...", GREEN)
    print()

    replay_recorder = VCRRecorder(output_dir=str(vcr_dir))
    outputs, ledger = cache.replay(
        task=task,
        recorder=replay_recorder,
    )

    for i, output in enumerate(outputs):
        action = output.get("action", output.get("plan", "replayed"))
        step("  ⚡", f"Step {i+1}: {action} {DIM}(from cache){RESET}", GREEN)

    print()
    step("✅", f"{GREEN}{BOLD}COMPLETED IN {ledger.replay_latency_ms:.0f}ms — $0.00 in LLM calls{RESET}")
    print()

    # ── THE MONEY SHOT: Cost Comparison ──────────────────────────────
    banner("💰 THE COST COMPARISON — This Number Hits Different", YELLOW)

    cost_box("RUN 1: Original", run1_tokens, run1_cost, run1_latency, RED)
    print()
    cost_box("RUN 2: Golden Replay", ledger.replay_tokens, ledger.replay_cost_usd, ledger.replay_latency_ms, GREEN)

    print()
    print(f"  {BOLD}{GREEN}┌─────────────────────────────────────────┐")
    print(f"  │  💰 SAVINGS                              │")
    print(f"  │  Tokens saved:  {ledger.tokens_saved:>10,}                │")
    print(f"  │  Cost saved:    ${ledger.cost_saved_usd:>9.4f}                │")
    print(f"  │  Time saved:    {ledger.time_saved_ms:>8.0f}ms                │")
    print(f"  │  Reduction:     {ledger.savings_percent:>7.0f}%                 │")
    print(f"  └─────────────────────────────────────────┘{RESET}")

    print()
    banner(
        "PLAN → BUILD → FAIL → REWIND → FIX → SUCCEED → NEVER PAY TWICE\n"
        "\n"
        "Nobody has closed this loop end-to-end.\n"
        "agent-vcr just did.\n"
        "\n"
        "pip install ai-agent-vcr",
        MAGENTA,
    )


if __name__ == "__main__":
    run_full_demo()
